:: SET DLC_ROOT=
:: SET DLC_NAME=
:: SODA_SIM_ROOT=

SET DLC_NAME=CitySampleProject
SET MAPS=Big_City_LVL+Small_City_LVL
SET CUSTOM_CONFIG=CitySample
SET DLC_MOUNT_TARGET=%DLC_ROOT%\CitySample
SET DLC_MOUNT_LINK=%SODA_SIM_ROOT%\Content
SET EXT_PLUGIN_NAME=