:: SET DLC_ROOT=
:: SET DLC_NAME=
:: SODA_SIM_ROOT=

SET DLC_NAME=MeadowEnvironmentSet
SET MAPS=Meadow_Environment_Set_Map
SET CUSTOM_CONFIG=
SET DLC_MOUNT_TARGET=%DLC_ROOT%\%DLC_NAME%
SET DLC_MOUNT_LINK=%SODA_SIM_ROOT%\Content
SET EXT_PLUGIN_NAME=