:: SET DLC_ROOT=
:: SET DLC_NAME=
:: SODA_SIM_ROOT=

SET DLC_NAME=CarlaProject
SET MAPS=Town01_Opt+Town02_Opt+Town03_Opt+Town04_Opt+Town05_Opt+Town06_Opt+Town07_Opt+Town10HD_Opt+Town11+Town12+Town13+Town15
SET CUSTOM_CONFIG=Carla
SET DLC_MOUNT_TARGET=%DLC_ROOT%\Carla
SET DLC_MOUNT_LINK=%SODA_SIM_ROOT%\Content\Carla
SET EXT_PLUGIN_NAME=